### ISSUE TITLE
numpy.arange is half-open --> you exclude the last bin

### ISSUE THREAD

**Issue by m-haas** [GEMScienceTools/hmtk#39]
By chance I stumbled on this:
In several functions you use the numpy.arange method.
The way you use it affects e.g.
the plot_depth_histogram method in
hmtk/plotting/seismicity/catalogue_plots.py
where you exclude the largest depth in the catalogue from the plot.

Instead of
numpy.arange(0.,max_depth,bin_width)
I'd do something like:
numpy.arange(0.,max_depth+bin_width,bin_width)

I saw several other lines where this might cause problems

**Comment by g-weatherill** [comment]
Hopefully, this last PR fixes the issue.
